// Generated by scripts/build-xano-custom-fields.js. No database writes or network calls.
function "pipechat/custom_fields" {
  input {
    json payload
    text mode
  }
  stack {
    api.lambda {
      code = ```
        const fields={"account":"Company","stage":"Stage","value":"Value","close":"Close date","owner":"Owner","next":"Next step","follow":"Follow-up","notes":"Notes"},stages=["Discovery","Warm","Proposal Sent","Negotiation","At Risk","Won","Lost"];
        const normalize=value => String(value ?? '').normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim().replace(/\s+/g, ' ');
        function fieldName(value, customFields = []) {
            const custom = customFields.find(field=>field.id===value || normalize(field.name)===normalize(value));
            if (custom) return custom.id;
            const key = normalize(value).replace(/[\s-]+/g, '_');
            const aliases={ company:'account', name:'account', status:'stage', amount:'value', close_date:'close', next_step:'next', follow_up:'follow', note:'notes', rep:'owner', salesperson:'owner' };
            return Object.hasOwn(aliases,key)?aliases[key]:key;
          }
        function validateCustomFields(input = []) {
            if (!Array.isArray(input) || input.length > 20) throw new Error('A CRM supports up to 20 custom text fields.');
            const ids = new Set(), names = new Set(Object.values(fields).map(normalize));
            return input.map(field => {
              if (!field || typeof field.id !== 'string' || !/^cf_[a-z0-9_]{1,60}$/.test(field.id) || ids.has(field.id) || field.type !== 'text') throw new Error('Invalid custom field definition.');
              if (typeof field.name !== 'string') throw new Error('Enter a field name.');
              const name = field.name.trim(), key = normalize(name);
              if (!name || name.length > 60 || /[\x00-\x1f\x7f]/.test(name)) throw new Error('Field names must contain 1 to 60 readable characters.');
              if (names.has(key) || [...Object.keys(fields),'id','activity','health','history','__proto__','prototype','constructor'].includes(fieldName(name))) throw new Error('A field with that name already exists or is reserved.');
              ids.add(field.id); names.add(key);
              return {id:field.id,name,type:'text'};
            });
          }
        function fieldsFor(customFields = []) {
            return {...fields,...Object.fromEntries(validateCustomFields(customFields).map(field=>[field.id,field.name]))};
          }
        function date(value) {
            const text = String(value || '').trim();
            let parts = /^(\d{4})-(\d{2})-(\d{2})$/.exec(text);
            if (parts) {
              const d = new Date(Date.UTC(+parts[1], +parts[2] - 1, +parts[3]));
              return d.toISOString().slice(0, 10) === text ? d : null;
            }
            parts = /^(Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)\s+(\d{1,2}),?\s+(\d{4})$/i.exec(text);
            if (!parts) return null;
            const month = ['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'].indexOf(parts[1].slice(0,3).toLowerCase());
            const d = new Date(Date.UTC(+parts[3], month, +parts[2]));
            return d.getUTCMonth() === month && d.getUTCDate() === +parts[2] ? d : null;
          }
        function validateValue(field, value, customFields = []) {
            const labels=fieldsFor(customFields);
            if (!Object.hasOwn(labels, field)) throw new Error('This table does not contain that field.');
            if (value === null || value === undefined) throw new Error(`Specify a value for ${labels[field]}.`);
            if (field.startsWith('cf_') && typeof value !== 'string') throw new Error('Custom text fields require text.');
            if (field === 'value') {
              if (String(value).trim() === '' || typeof value === 'boolean' || typeof value === 'object') throw new Error('Enter a valid deal value.');
              const amount = Number(value);
              if (!Number.isFinite(amount) || amount < 0 || amount > 1e12) throw new Error('Value must be a number between 0 and 1 trillion.');
              return Math.round(amount * 100) / 100;
            }
            let text = String(value).trim();
            if (text.length > 12000) throw new Error('This field is too long.');
            if (field === 'account' && !text) throw new Error('Company name is required.');
            if (field === 'stage') {
              const aliases = { proposal:'Proposal Sent', quote:'Proposal Sent', 'closed won':'Won', 'closed lost':'Lost' };
              text = aliases[normalize(text)] || stages.find(stage => normalize(stage) === normalize(text));
              if (!text) throw new Error('Choose one of the existing stages.');
            }
            if (field === 'close' && text) {
              const parsed = date(text);
              if (!parsed) throw new Error('Use a complete, valid close date, including its year.');
              text = parsed.toISOString().slice(0, 10);
            }
            return text;
          }
        function validateStoredValue(field, value, customFields = []) {
            if (field === 'value' && (value === null || value === '')) return null;
            if (['account','stage'].includes(field) && value === '') return '';
            return validateValue(field,value,customFields);
          }
        function customValues(record, customFields = []) {
            const definitions=validateCustomFields(customFields), allowed=new Set(definitions.map(field=>field.id));
            if (Object.keys(record).some(key=>key.startsWith('cf_')&&!allowed.has(key))) throw new Error('Unknown custom field. Refresh before saving.');
            return Object.fromEntries(definitions.map(field=>[field.id,validateStoredValue(field.id,record[field.id]??'',definitions)]));
          }
        
        try {
          const payload=$input.payload;
          if($input.mode==='write'){
            const fields=validateCustomFields(payload.customFields);
            if(!Array.isArray(payload.deals)||payload.deals.length>2000)throw new Error('Invalid rows');
            const cells={};
            for(const row of payload.deals){
              if(!Number.isSafeInteger(row.id)||row.id<1||Object.hasOwn(cells,String(row.id)))throw new Error('Invalid row ID');
              cells[String(row.id)]=customValues(row,fields);
            }
            return {ok:true,data:{fields,cells}};
          }
          if($input.mode==='read'){
            const data=payload.customData??{fields:[],cells:{}};
            const fields=validateCustomFields(data.fields);
            if(!data.cells||typeof data.cells!=='object'||Array.isArray(data.cells))throw new Error('Invalid custom cells');
            const deals=payload.deals.map(row=>({...row,...customValues(data.cells[String(row.id)]??{},fields)}));
            return {ok:true,data:{deals,customFields:fields,updatedAt:payload.updatedAt}};
          }
          return {ok:false};
        } catch { return {ok:false}; }
        
        ```
      timeout = 5
    } as $result
    precondition ($result.ok) {
      error_type = "inputerror"
      error = "Invalid custom field definitions or values"
    }
  }
  response = $result.data
}
